### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by leonidas2522** [developeranaz/Mega.nz-Rclone-Index-Heroku#15]
"Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail'"

just happened today.

**Comment by developeranaz** [comment]
wait

**Comment by developeranaz** [comment]
ohh i tried editing the entire app 🤦‍♂️
it was not my mistake, it maybe rclone or mega's
Now its working fine.
