### ISSUE TITLE
Do you have access to our Mega Drive ?

### ISSUE THREAD

**Issue by nadeem49** [developeranaz/Mega.nz-Rclone-Index-Heroku#18]
How did you import **donate-developeranaz.txt** into my Mega drive ? Do you have our credentials? 

Please clarify. Thanks for the index.

**Comment by developeranaz** [comment]
> How did you import **donate-developeranaz.txt** into my Mega drive ? Do you have our credentials?
> 
> Please clarify. Thanks for the index.

nop, don't be scared , i will never do that 😥.

i don't have access to others credentials.
i added a line in entrypoint.sh file [line 8]in the webapp to copy donate-developeranaz.txt to their mega index in app start. 


entrypoint.sh :
simply Its just an automation script that copies that file to your mega account and after that it will index your files.

You can permanently remove that by changing or removing
 line 8 on entrypoint.sh file and deploy using your's webapp.

**Comment by developeranaz** [comment]
![Screenshot_20211018_164153](https://user-images.githubusercontent.com/71500526/137720172-213e56e1-9210-4d19-b8fb-01650ebe6809.jpg)
this is the line

**Comment by nadeem49** [comment]
Thanks for the clarification. If you dont want to scare others like me. It would be better to avoid this step as it looks like you got access to others drive.  

Also please mention in Readme.md that you cannot get access to anyone's credentials. This will clarify doubts in people.

Is there a possibility to add a 2FA authenticated drive ?

**Comment by developeranaz** [comment]
Thank you for providing that valuable information.😅
I will add it in the readme in the next update
and 2FA authenticated accounts can't be served because of their security.
