### ISSUE TITLE
Frequent Errors and Max download speed of 200 kbps

### ISSUE THREAD

**Issue by astro204** [developeranaz/Mega.nz-Rclone-Index-Heroku#19]
The downloads just stop in between many of the times and show an error. Also i cant seem to get more than 200kbps speed per download. Is there a max simultaneous downloads or max chunks per download limit?

**Comment by developeranaz** [comment]
Use download manager like Aria2 ,FDM ,XDM or ADM and increase number of threads per download.

**Comment by astro204** [comment]
The thing is that i am using fdm, getting http errors, tho increasing connections to server did increase the download speeds up to a net speed of 4 MB/s , which is not really my max speed but im happy with it. Is there any solution for the errors?

**Comment by developeranaz** [comment]
No solution , Maybe heroku can't have that much capability but there is a quota limit for mega, after every 2gb you need to restart his dynos, maybe thats the problem.

Maybe some errors can be resolved by creating multiple index and add mirror links from different index of same file.
I think FDM has a mirror link download option

**Comment by astro204** [comment]
what do you mean by creating multiple indexes?

**Comment by developeranaz** [comment]
> what do you mean by creating multiple indexes?

means deploying this webapp multiple times in heroku with same mega account, this helps mirroring your mega from different servers

**Comment by astro204** [comment]
How many times do you recommend? correct me if I'm wrong, I don't think fdm does have mirror links option, which downloader would you recommend which does have the option?

**Comment by developeranaz** [comment]
FDM in android had that option- please check again in pc
aria2 (command line) / aria2 web gui had that option named (parallel download)
don't know others

**Comment by astro204** [comment]
FDM is free download manager right? I cant seem to find the option.  i might start using aria2

**Comment by developeranaz** [comment]
aria2 for windows is hard
FDM has mirror link option
![WHfM3cOgVW](https://user-images.githubusercontent.com/71500526/138307264-6d021588-a654-41b4-a6bc-bbd256d7906a.gif)

**Comment by astro204** [comment]
Thanks so very much! You're the best.
